// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6HZWZbmJ_JsdPbheb6EMlpGm6LRnhYsc',
    appId: '1:898370900411:web:c71f0b9c9e5d5d7f86349e',
    messagingSenderId: '898370900411',
    projectId: 'sockeyway',
    authDomain: 'sockeyway.firebaseapp.com',
    storageBucket: 'sockeyway.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRehyg62iyfeZpqhV5RdmkJhHMhsNBqTY',
    appId: '1:898370900411:android:aa724328b35c5b4286349e',
    messagingSenderId: '898370900411',
    projectId: 'sockeyway',
    storageBucket: 'sockeyway.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaSd8HLIGn171bjP_jMnkW7lEw3lJ-o94',
    appId: '1:898370900411:ios:d4dd2c26cc9c1b2f86349e',
    messagingSenderId: '898370900411',
    projectId: 'sockeyway',
    storageBucket: 'sockeyway.appspot.com',
    iosBundleId: 'com.example.sockeywayWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaSd8HLIGn171bjP_jMnkW7lEw3lJ-o94',
    appId: '1:898370900411:ios:7250385100a4649186349e',
    messagingSenderId: '898370900411',
    projectId: 'sockeyway',
    storageBucket: 'sockeyway.appspot.com',
    iosBundleId: 'com.example.sockeywayWeb.RunnerTests',
  );
}
